// AUTO-GENERATED by scripts/build_deploy_bundle.js — 이 파일을 직접 고치지 마세요.
// 수정하려면 src/daily-position-monitor.src.js를 고친 뒤 `node scripts/build_deploy_bundle.js`를 다시 실행하세요.
// Daily_Position_Monitor.js
// n8n Function node — 장 마감 후 실행 (16:00 KST)
// 목적: store.weeklyRecommendations의 활성 포지션에 트레일링 스탑 적용
//       스탑 레벨 상승 시 Telegram 알림 발송
// 공통 포맷/유틸 헬퍼 — 여러 노드 소스에 복붙되어 있던 것을 통합.
//
// 주의(swing-scanner.src.js는 이 pct()를 쓰지 않는다): swing_scanner_code.js의 기존 pct()는
// 부호를 붙이지 않는 버전이었다(호출부 템플릿에서 '(+' / '(-'를 직접 문자열로 적어왔기
// 때문). 여기 pct()는 weekly_reporter/Daily_Position_Monitor가 쓰던, 값의 부호에 따라
// +/-를 스스로 붙이는 버전이다. 동작을 하나로 강제 통합하면 swing-scanner 쪽 메시지에
// 부호가 두 번 붙는 회귀가 생기므로, swing-scanner.src.js는 의도적으로 자기 파일 안에
// 부호 없는 pct()를 그대로 로컬로 유지한다.
function pct(r) {
  return (r >= 0 ? '+' : '') + (Number(r) * 100).toFixed(1) + '%';
}

// to0(): Daily_Position_Monitor의 기존 버전은 Number() 방어가 없었다(비정상 입력 시 'NaN'
// 문자열 노출). swing_scanner_code.js의 방어적인 버전(Number(n) || 0)을 정본으로 채택.
function to0(n) {
  return Math.round(Number(n) || 0).toLocaleString('ko-KR');
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// Telegram sendMessage 래퍼 — 여러 노드 소스에 복붙된 POST 요청을 통합.
// send()는 에러를 스스로 삼키지 않는다(순수 http() 호출 그대로) — 호출부마다
// try/catch 유무가 달랐던 기존 동작을 그대로 보존하기 위함.
function createTelegram(http, botToken, chatId) {
  const send = (text) => http({
    method: 'POST',
    url: 'https://api.telegram.org/bot' + botToken + '/sendMessage',
    json: true,
    body: { chat_id: chatId, text },
  });
  return { send };
}

// Naver 일봉/분봉 조회 — swing_scanner_code.js / weekly_reporter_code.js / Daily_Position_Monitor.js에
// 각각 독립적으로(그리고 서로 다르게) 구현돼 있던 것을 통합.
//
// 통합하며 실제로 확인된 차이(리팩토링 계획서 "결정 필요 항목" 참고)와 채택안:
// - 에러 처리: swing_scanner/Daily_Position_Monitor는 에러를 그대로 throw, weekly_reporter는
//   try/catch로 null 반환 → null 반환으로 통일(모든 호출부가 이미 null 체크 로직을 가짐).
// - Accept-Language: swing_scanner만 'en;q=0.8'까지 포함 → 더 넓은 값을 채택.
// - encoding: 'utf8': weekly_reporter만 빠져 있었음 → 포함으로 통일.
// - 응답 형태 정규화: Daily_Position_Monitor만 res.body/data/result/chartPriceList 언래핑을
//   했었음 → 다른 두 곳도 이 언래핑 혜택을 받도록 포함.
//
// [2026-07-25 BUGFIX] 통합 과정에서 swing_scanner_code.js에만 있던 Buffer/BOM/문자열
// JSON 응답 처리(_normalizeNaverResp, 2026-03-30 naver_resp_normalize 패치로 추가됨)가
// 빠져 있었다. 이 상태에서는 Naver가 응답을 문자열(BOM 포함)이나 Buffer로 반환하는 경우
// 정규화에 실패해 모든 종목이 null을 반환받아 주간 리포트가 "총추천 N건 │ 진입 0건"으로
// 통째로 비어버리는 문제가 재발한다(2026-03-30 "0/1348/0" 장애와 동일 유형). 아래에서
// 그 방어 로직을 다시 포함시킨다.
function createNaverClient(http) {
  const baseHeaders = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    'Referer': 'https://finance.naver.com/',
    'Accept': 'application/json',
    'Accept-Charset': 'utf-8',
    'Accept-Language': 'ko-KR,ko;q=0.9,en;q=0.8',
  };

  const normalize = (resp) => {
    let r = resp;
    if (r === null || r === undefined) return null;
    if (typeof Buffer !== 'undefined' && Buffer.isBuffer(r)) r = r.toString('utf8');
    if (typeof r === 'string') {
      const cleaned = r.replace(/^\uFEFF/, '').trim(); // BOM 및 앞뒤 공백 제거
      try { r = JSON.parse(cleaned); } catch (_) { return null; }
    }
    const items = Array.isArray(r)
      ? r
      : (r && (r.body || r.data || r.result || r.chartPriceList));
    return (Array.isArray(items) && items.length > 0) ? items : null;
  };

  const fetchDaily = async (code, startDate, endDate) => {
    const url = `https://api.stock.naver.com/chart/domestic/item/${code}/day?startDateTime=${startDate}&endDateTime=${endDate}`;
    try {
      const resp = await http({ method: 'GET', url, json: true, headers: baseHeaders, encoding: 'utf8' });
      return normalize(resp);
    } catch (e) {
      return null;
    }
  };

  const fetchMinute = async (code, dateStr) => {
    const ymd = dateStr.replace(/-/g, '');
    const url = `https://api.stock.naver.com/chart/domestic/item/${code}/minute?startDateTime=${ymd}000000&endDateTime=${ymd}235959`;
    try {
      const resp = await http({ method: 'GET', url, json: true, headers: baseHeaders, encoding: 'utf8' });
      return normalize(resp);
    } catch (e) {
      return null;
    }
  };

  return { fetchDaily, fetchMinute };
}

// KRX 휴장일 — 단일 진실공급원 (기존 swing_scanner_code.js / weekly_reporter_code.js에 각각
// 복붙되어 있던 배열을 통합). Daily_Healthcheck의 HOLIDAYS_2026는 이 목록보다 짧아서
// '2026-07-17'이 빠져 있었다 — 이 파일로 통합하면서 그 누락도 함께 고친다.
const HOLIDAYS = ['2025-01-01','2025-01-28','2025-01-29','2025-01-30','2025-03-01','2025-03-03','2025-05-05','2025-05-06','2025-06-06','2025-08-15','2025-10-03','2025-10-06','2025-10-07','2025-10-08','2025-10-09','2025-12-25','2026-01-01','2026-02-16','2026-02-17','2026-02-18','2026-03-01','2026-03-02','2026-05-05','2026-05-24','2026-05-25','2026-06-03','2026-06-06','2026-07-17','2026-08-15','2026-08-17','2026-09-24','2026-09-25','2026-09-26','2026-10-03','2026-10-05','2026-10-09','2026-12-25'];

function isHoliday(dateStr) {
  return HOLIDAYS.includes(dateStr);
}

function isWeekend(dow) {
  return dow === 0 || dow === 6;
}

// 트레일링 스탑 계산 — Daily_Position_Monitor(실시간 갱신)와 weekly_reporter(사후 재구성)가
// 동일한 로직을 공유해야 리포트의 손절일 판정이 실제 운영 동작과 일치한다.
const TRAIL_BE_GAIN   = 0.03;   // 수익률 3% 이상: 손절→진입가(본전)
const TRAIL_5_GAIN    = 0.05;   // 수익률 5% 이상: 손절→고점−ATR×1.5
const TRAIL_10_GAIN   = 0.10;   // 수익률 10% 이상: 손절→고점−ATR×1.0
const TRAIL_15_GAIN   = 0.15;   // 수익률 15% 이상: 손절→고점−ATR×0.7
const TRAIL_MULT_5    = 1.5;
const TRAIL_MULT_10   = 1.0;
const TRAIL_MULT_15   = 0.7;

function getAtr(atrAbs, currentHigh, currentLow, currentClose) {
  if (atrAbs && Number.isFinite(atrAbs) && atrAbs > 0) return atrAbs;
  // atrAbs 없을 때: 당일 고-저 범위로 근사
  return Math.max(currentHigh - currentLow, currentClose * 0.02);
}

// currentGain은 장중 고가 기준으로 넘겨야 한다([A안 2026-08-22] 종가 기준으로 게이팅하면
// 장중 목표가 터치 후 종가가 밀릴 때 본전 스탑이 전혀 발동하지 않는 문제가 있었음).
function calcTrailingStop(entry, currentHigh, atr, currentGain, existingStop) {
  let newStop = existingStop;

  if (currentGain >= TRAIL_15_GAIN) {
    newStop = currentHigh - atr * TRAIL_MULT_15;
  } else if (currentGain >= TRAIL_10_GAIN) {
    newStop = currentHigh - atr * TRAIL_MULT_10;
  } else if (currentGain >= TRAIL_5_GAIN) {
    newStop = currentHigh - atr * TRAIL_MULT_5;
  } else if (currentGain >= TRAIL_BE_GAIN) {
    newStop = entry; // 본전 스탑
  }

  // 스탑은 절대 낮아지지 않음 (트레일링)
  return Math.max(newStop, existingStop);
}


const BOT  = '8366696724:AAHROcjGoQEn9BziD-sYdAu3ZuaolwtkgLE';
const CHAT = '523002062';

const NL = '\n';

const store = this.getWorkflowStaticData('global');
const http = async (o) => await this.helpers.httpRequest(Object.assign({ timeout: 30000 }, o));
const telegram = createTelegram(http, BOT, CHAT);
const naver = createNaverClient(http);

// ===== KST 기준 오늘 날짜 =====
const now = new Date();
const kst = new Date(now.getTime() + 9 * 60 * 60 * 1000);
const today = `${kst.getUTCFullYear()}-${String(kst.getUTCMonth() + 1).padStart(2, '0')}-${String(kst.getUTCDate()).padStart(2, '0')}`;

if (isHoliday(today)) {
  return [{ json: { skipped: true, reason: 'Holiday', today } }];
}

// ===== 네이버 일봉 데이터 조회 =====
async function fetchDailyClose(code) {
  const kstNow = new Date(Date.now() + 9 * 3600000);
  const ed = kstNow.toISOString().slice(0, 10).replace(/-/g, '') + '235959';
  const sdDate = new Date(kstNow.getTime() - 10 * 24 * 3600000);
  const sd = sdDate.toISOString().slice(0, 10).replace(/-/g, '') + '000000';
  const items = await naver.fetchDaily(code, sd, ed);
  if (!items) return null;
  // 오름차순 정렬 기준 마지막 항목이 최신, 그 앞이 전일
  const latest = items[items.length - 1];
  const prev = items.length >= 2 ? items[items.length - 2] : null;
  return {
    close: Number(latest.closePrice || latest.close),
    high:  Number(latest.highPrice  || latest.high),
    low:   Number(latest.lowPrice   || latest.low),
    prevClose: prev ? Number(prev.closePrice || prev.close) : null,
    latestDate: latest.localDate,
  };
}

// ===== 급락 감지 (트레일링 스탑 도달 여부와 무관하게, 전일 종가 대비 급락 시 즉시 경고) =====
const SHOCK_DROP_THRESH = -0.05; // 당일 종가가 전일 종가 대비 -5% 이상 하락 시 트리거

function computeDayChangePct(close, prevClose) {
  if (!prevClose || prevClose <= 0) return null;
  return (close - prevClose) / prevClose;
}

// ===== 활성 포지션 수집 =====
const weeklyRecs = store.weeklyRecommendations || {};
const allDates = Object.keys(weeklyRecs).sort();

const activePositions = [];
for (const dateKey of allDates) {
  for (const rec of (weeklyRecs[dateKey] || [])) {
    if (rec.type !== 'swing') continue;
    // 만료 여부 확인 (보유 기간 초과 시 스킵)
    const holdDays = rec.holdingDays || 3;
    const entryDate = new Date(rec.date || dateKey);
    const expiry = new Date(entryDate.getTime() + holdDays * 1.4 * 24 * 60 * 60 * 1000); // 거래일 근사
    if (expiry < now) continue;
    activePositions.push(rec);
  }
}

if (!activePositions.length) {
  return [{ json: { message: '활성 포지션 없음', today, checked: 0 } }];
}

// ===== 각 포지션 처리 =====
const alerts = [];
let updated = 0;
let shockCount = 0;

for (const rec of activePositions) {
  const candle = await fetchDailyClose(rec.code);
  if (!candle) continue;

  const { close, high, low, prevClose, latestDate } = candle;
  const entry = rec.entry;
  if (!entry || entry <= 0) continue;

  const currentGain = (close - entry) / entry;
  // [A안 2026-08-22] 트레일링 티어 판정은 종가 대신 장중 고가 기준으로 변경.
  // 종가 기준이면 장중 1차목표(고가 기준) 터치 후 종가가 밀릴 때 본전 스탑이
  // 전혀 발동하지 않아 초기 손절가(최대 -8%)가 그대로 남는 문제가 있었음.
  const tierGain = (high - entry) / entry;
  const atr = getAtr(rec.atrAbs, high, low, close);
  const oldStop = rec.stop || 0;

  const newStop = calcTrailingStop(entry, high, atr, tierGain, oldStop);

  // 스탑 레벨 의미있게 상승했을 때만 알림 (최소 0.3% 이상 상승)
  const stopRaised = newStop > oldStop * 1.003;

  if (stopRaised) {
    // store 업데이트
    rec.stop = newStop;
    updated++;

    const gainPct = pct(currentGain);
    const oldStopPct = entry > 0 ? pct((oldStop - entry) / entry) : 'N/A';
    const newStopPct = entry > 0 ? pct((newStop - entry) / entry) : 'N/A';

    alerts.push(
      '[🛡️ 스탑 상향] ' + (rec.name || rec.code) + '(' + rec.code + ')' + NL +
      '현재가: ' + to0(close) + '원 (' + gainPct + ')' + NL +
      '손절가: ' + to0(oldStop) + '원(' + oldStopPct + ') → ' + to0(newStop) + '원(' + newStopPct + ')' + NL +
      'ATR: ' + to0(atr) + '원'
    );
  }

  // 급락 경고: 트레일링 스탑 도달 여부와 무관하게, 전일 종가 대비 급락 시 즉시 알림
  // (오늘 봉이 아직 안 올라온 경우 — 휴장일 지연 등 — 오래된 등락을 오늘 급락으로 오판하지 않도록 가드)
  const latestDateFormatted = latestDate ? `${latestDate.slice(0,4)}-${latestDate.slice(4,6)}-${latestDate.slice(6,8)}` : null;
  const dayChangePct = computeDayChangePct(close, prevClose);
  if (latestDateFormatted === today && dayChangePct !== null && dayChangePct <= SHOCK_DROP_THRESH) {
    shockCount++;
    alerts.push(
      '[⚠️ 급락 경고] ' + (rec.name || rec.code) + '(' + rec.code + ')' + NL +
      '전일종가 대비: ' + pct(dayChangePct) + NL +
      '현재가: ' + to0(close) + '원 │ 진입가 대비: ' + pct(currentGain) + NL +
      '시장 변동성 확대 — 포지션 재검토 권장'
    );
  }
}

// ===== Telegram 알림 발송 =====
for (const alertMsg of alerts) {
  try {
    await telegram.send(alertMsg);
    await new Promise((r) => setTimeout(r, 500));
  } catch {
    // 알림 실패는 무시
  }
}

// store 반영 (n8n Globals 노드가 있다면 별도 Set 노드로 저장 필요)
// store.weeklyRecommendations는 이미 참조로 수정됨

return [{
  json: {
    today,
    activePositions: activePositions.length,
    updated,
    shockAlerts: shockCount,
    alertsSent: alerts.length,
    message: (updated > 0 || shockCount > 0)
      ? `스탑 상향 ${updated}건, 급락 경고 ${shockCount}건 알림 발송`
      : '스탑 상향/급락 없음 (모든 포지션 정상)',
  }
}];
