// AUTO-GENERATED by scripts/build_deploy_bundle.js — 이 파일을 직접 고치지 마세요.
// 수정하려면 src/weekly-reporter.src.js를 고친 뒤 `node scripts/build_deploy_bundle.js`를 다시 실행하세요.
// KRX 휴장일 — 단일 진실공급원 (기존 swing_scanner_code.js / weekly_reporter_code.js에 각각
// 복붙되어 있던 배열을 통합). Daily_Healthcheck의 HOLIDAYS_2026는 이 목록보다 짧아서
// '2026-07-17'이 빠져 있었다 — 이 파일로 통합하면서 그 누락도 함께 고친다.
const HOLIDAYS = ['2025-01-01','2025-01-28','2025-01-29','2025-01-30','2025-03-01','2025-03-03','2025-05-05','2025-05-06','2025-06-06','2025-08-15','2025-10-03','2025-10-06','2025-10-07','2025-10-08','2025-10-09','2025-12-25','2026-01-01','2026-02-16','2026-02-17','2026-02-18','2026-03-01','2026-03-02','2026-05-05','2026-05-24','2026-05-25','2026-06-03','2026-06-06','2026-07-17','2026-08-15','2026-08-17','2026-09-24','2026-09-25','2026-09-26','2026-10-03','2026-10-05','2026-10-09','2026-12-25'];

function isHoliday(dateStr) {
  return HOLIDAYS.includes(dateStr);
}

function isWeekend(dow) {
  return dow === 0 || dow === 6;
}

// 공통 포맷/유틸 헬퍼 — 여러 노드 소스에 복붙되어 있던 것을 통합.
//
// 주의(swing-scanner.src.js는 이 pct()를 쓰지 않는다): swing_scanner_code.js의 기존 pct()는
// 부호를 붙이지 않는 버전이었다(호출부 템플릿에서 '(+' / '(-'를 직접 문자열로 적어왔기
// 때문). 여기 pct()는 weekly_reporter/Daily_Position_Monitor가 쓰던, 값의 부호에 따라
// +/-를 스스로 붙이는 버전이다. 동작을 하나로 강제 통합하면 swing-scanner 쪽 메시지에
// 부호가 두 번 붙는 회귀가 생기므로, swing-scanner.src.js는 의도적으로 자기 파일 안에
// 부호 없는 pct()를 그대로 로컬로 유지한다.
function pct(r) {
  return (r >= 0 ? '+' : '') + (Number(r) * 100).toFixed(1) + '%';
}

// to0(): Daily_Position_Monitor의 기존 버전은 Number() 방어가 없었다(비정상 입력 시 'NaN'
// 문자열 노출). swing_scanner_code.js의 방어적인 버전(Number(n) || 0)을 정본으로 채택.
function to0(n) {
  return Math.round(Number(n) || 0).toLocaleString('ko-KR');
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// Telegram sendMessage 래퍼 — 여러 노드 소스에 복붙된 POST 요청을 통합.
// send()는 에러를 스스로 삼키지 않는다(순수 http() 호출 그대로) — 호출부마다
// try/catch 유무가 달랐던 기존 동작을 그대로 보존하기 위함.
function createTelegram(http, botToken, chatId) {
  const send = (text) => http({
    method: 'POST',
    url: 'https://api.telegram.org/bot' + botToken + '/sendMessage',
    json: true,
    body: { chat_id: chatId, text },
  });
  return { send };
}

// Naver 일봉/분봉 조회 — swing_scanner_code.js / weekly_reporter_code.js / Daily_Position_Monitor.js에
// 각각 독립적으로(그리고 서로 다르게) 구현돼 있던 것을 통합.
//
// 통합하며 실제로 확인된 차이(리팩토링 계획서 "결정 필요 항목" 참고)와 채택안:
// - 에러 처리: swing_scanner/Daily_Position_Monitor는 에러를 그대로 throw, weekly_reporter는
//   try/catch로 null 반환 → null 반환으로 통일(모든 호출부가 이미 null 체크 로직을 가짐).
// - Accept-Language: swing_scanner만 'en;q=0.8'까지 포함 → 더 넓은 값을 채택.
// - encoding: 'utf8': weekly_reporter만 빠져 있었음 → 포함으로 통일.
// - 응답 형태 정규화: Daily_Position_Monitor만 res.body/data/result/chartPriceList 언래핑을
//   했었음 → 다른 두 곳도 이 언래핑 혜택을 받도록 포함.
//
// [2026-07-25 BUGFIX] 통합 과정에서 swing_scanner_code.js에만 있던 Buffer/BOM/문자열
// JSON 응답 처리(_normalizeNaverResp, 2026-03-30 naver_resp_normalize 패치로 추가됨)가
// 빠져 있었다. 이 상태에서는 Naver가 응답을 문자열(BOM 포함)이나 Buffer로 반환하는 경우
// 정규화에 실패해 모든 종목이 null을 반환받아 주간 리포트가 "총추천 N건 │ 진입 0건"으로
// 통째로 비어버리는 문제가 재발한다(2026-03-30 "0/1348/0" 장애와 동일 유형). 아래에서
// 그 방어 로직을 다시 포함시킨다.
function createNaverClient(http) {
  const baseHeaders = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    'Referer': 'https://finance.naver.com/',
    'Accept': 'application/json',
    'Accept-Charset': 'utf-8',
    'Accept-Language': 'ko-KR,ko;q=0.9,en;q=0.8',
  };

  const normalize = (resp) => {
    let r = resp;
    if (r === null || r === undefined) return null;
    if (typeof Buffer !== 'undefined' && Buffer.isBuffer(r)) r = r.toString('utf8');
    if (typeof r === 'string') {
      const cleaned = r.replace(/^\uFEFF/, '').trim(); // BOM 및 앞뒤 공백 제거
      try { r = JSON.parse(cleaned); } catch (_) { return null; }
    }
    const items = Array.isArray(r)
      ? r
      : (r && (r.body || r.data || r.result || r.chartPriceList));
    return (Array.isArray(items) && items.length > 0) ? items : null;
  };

  const fetchDaily = async (code, startDate, endDate) => {
    const url = `https://api.stock.naver.com/chart/domestic/item/${code}/day?startDateTime=${startDate}&endDateTime=${endDate}`;
    try {
      const resp = await http({ method: 'GET', url, json: true, headers: baseHeaders, encoding: 'utf8' });
      return normalize(resp);
    } catch (e) {
      return null;
    }
  };

  const fetchMinute = async (code, dateStr) => {
    const ymd = dateStr.replace(/-/g, '');
    const url = `https://api.stock.naver.com/chart/domestic/item/${code}/minute?startDateTime=${ymd}000000&endDateTime=${ymd}235959`;
    try {
      const resp = await http({ method: 'GET', url, json: true, headers: baseHeaders, encoding: 'utf8' });
      return normalize(resp);
    } catch (e) {
      return null;
    }
  };

  return { fetchDaily, fetchMinute };
}

// 트레일링 스탑 계산 — Daily_Position_Monitor(실시간 갱신)와 weekly_reporter(사후 재구성)가
// 동일한 로직을 공유해야 리포트의 손절일 판정이 실제 운영 동작과 일치한다.
const TRAIL_BE_GAIN   = 0.03;   // 수익률 3% 이상: 손절→진입가(본전)
const TRAIL_5_GAIN    = 0.05;   // 수익률 5% 이상: 손절→고점−ATR×1.5
const TRAIL_10_GAIN   = 0.10;   // 수익률 10% 이상: 손절→고점−ATR×1.0
const TRAIL_15_GAIN   = 0.15;   // 수익률 15% 이상: 손절→고점−ATR×0.7
const TRAIL_MULT_5    = 1.5;
const TRAIL_MULT_10   = 1.0;
const TRAIL_MULT_15   = 0.7;

function getAtr(atrAbs, currentHigh, currentLow, currentClose) {
  if (atrAbs && Number.isFinite(atrAbs) && atrAbs > 0) return atrAbs;
  // atrAbs 없을 때: 당일 고-저 범위로 근사
  return Math.max(currentHigh - currentLow, currentClose * 0.02);
}

// currentGain은 장중 고가 기준으로 넘겨야 한다([A안 2026-08-22] 종가 기준으로 게이팅하면
// 장중 목표가 터치 후 종가가 밀릴 때 본전 스탑이 전혀 발동하지 않는 문제가 있었음).
function calcTrailingStop(entry, currentHigh, atr, currentGain, existingStop) {
  let newStop = existingStop;

  if (currentGain >= TRAIL_15_GAIN) {
    newStop = currentHigh - atr * TRAIL_MULT_15;
  } else if (currentGain >= TRAIL_10_GAIN) {
    newStop = currentHigh - atr * TRAIL_MULT_10;
  } else if (currentGain >= TRAIL_5_GAIN) {
    newStop = currentHigh - atr * TRAIL_MULT_5;
  } else if (currentGain >= TRAIL_BE_GAIN) {
    newStop = entry; // 본전 스탑
  }

  // 스탑은 절대 낮아지지 않음 (트레일링)
  return Math.max(newStop, existingStop);
}


const run = async function () {
  const BOT = '8366696724:AAHROcjGoQEn9BziD-sYdAu3ZuaolwtkgLE';
  const CHAT = '523002062';
  const http = async (o) => await this.helpers.httpRequest(Object.assign({ timeout: 30000 }, o));
  const NL = String.fromCharCode(10);
  const telegram = createTelegram(http, BOT, CHAT);
  const naver = createNaverClient(http);

  // ===== Logger initialization (n8n sandbox safe) =====
  let logger;
  try {
    const JsonLogger = require('./lib/logger');
    logger = new JsonLogger('weekly_reporter');
  } catch (e) {
    logger = { info:()=>{}, error:()=>{}, warning:()=>{}, debug:()=>{}, generateRequestId:(p)=>`${p}_${Date.now()}` };
  }
  const requestId = logger.generateRequestId('REPORT');
  logger.info('Weekly reporter started', { phase: 'initialization' }, requestId);

  const now = new Date();
  const kst = new Date(now.getTime() + 9 * 60 * 60 * 1000);
  const today = `${kst.getUTCFullYear()}-${String(kst.getUTCMonth() + 1).padStart(2, '0')}-${String(kst.getUTCDate()).padStart(2, '0')}`;

  const todayDow = kst.getUTCDay();
  if (!isWeekend(todayDow) && isHoliday(today)) return [{ json: { skipped: true, reason: 'Holiday', today } }];

  // 마지막 완료된 거래일 (토요일/장중 실행 시 Naver API가 비거래일 endDate에 빈 배열 반환 방지)
  const getPrevTradingDay = () => {
    let d = new Date(Date.now() + 9 * 3600000 - 24 * 3600000);
    for (let i = 0; i < 10; i++) {
      const dow = d.getUTCDay();
      const ds = d.toISOString().slice(0, 10);
      if (dow >= 1 && dow <= 5 && !isHoliday(ds)) return ds;
      d = new Date(d.getTime() - 24 * 3600000);
    }
    return new Date(Date.now() + 9 * 3600000 - 24 * 3600000).toISOString().slice(0, 10);
  };
  const prevTradingDay = getPrevTradingDay(); // 토요일 실행 시 금요일, 장중 실행 시 전일

  // N 거래일 후 날짜 계산 (주말/공휴일 제외)
  const addTradingDays = (startDateStr, n) => {
    const d = new Date(startDateStr + 'T00:00:00Z');
    let count = 0;
    while (count < n) {
      d.setUTCDate(d.getUTCDate() + 1);
      const dow = d.getUTCDay();
      const ds = `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}-${String(d.getUTCDate()).padStart(2, '0')}`;
      if (dow >= 1 && dow <= 5 && !isHoliday(ds)) count++;
    }
    return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}-${String(d.getUTCDate()).padStart(2, '0')}`;
  };

  // 지난 주 거래일 목록 (토요일 트리거 기준: 직전 월~금)
  const getWeekDates = (ref) => {
    const dates = [];
    const d = new Date(ref + 'T00:00:00Z');
    const dow = d.getUTCDay(); // 6=토
    const daysToFri = (dow === 6) ? 1 : (dow + 2); // Sat→1, Sun→2, Mon→3 ... Fri→7 (last week)
    const friday = new Date(d.getTime() - daysToFri * 24 * 60 * 60 * 1000);
    const monday = new Date(friday.getTime() - 4 * 24 * 60 * 60 * 1000);
    for (let i = 0; i < 5; i++) {
      const cur = new Date(monday.getTime() + i * 24 * 60 * 60 * 1000);
      const wd = cur.getUTCDay();
      const ds = `${cur.getUTCFullYear()}-${String(cur.getUTCMonth() + 1).padStart(2, '0')}-${String(cur.getUTCDate()).padStart(2, '0')}`;
      if (wd >= 1 && wd <= 5 && !isHoliday(ds)) dates.push(ds);
    }
    return dates;
  };

  const input = (items && items[0] && items[0].json) || {};
  const forceTest = !!input.forceTest;
  if (forceTest) {
    const msg = '[주간 스윙 리포트 테스트] 시스템 정상 작동 - ' + kst.toISOString().slice(0, 16).replace('T', ' ') + ' KST';
    try { await telegram.send(msg); } catch (e) {}
    return [{ json: { testSent: true } }];
  }

  const store = this.getWorkflowStaticData('global');
  if (!store.weeklyRecommendations) store.weeklyRecommendations = {};
  const weekDates = getWeekDates(today);
  if (weekDates.length === 0) return [{ json: { skipped: true, reason: 'No trading days this week' } }];

  // 이번 주 스윙 추천 수집 (scalping 제외 - swing 전용)
  const recs = [];
  for (const ds of weekDates) {
    const arr = store.weeklyRecommendations[ds] || [];
    for (const r of arr) {
      if (r.type === 'swing') recs.push({ ...r, date: ds });
    }
  }

  // [CARRYOVER] 지난주 이전 추천 중 보유기간이 이번 주까지 걸쳐있는 종목 별도 수집
  // (예: 지난주 목요일 추천 + holdingDays=5 → 이번주 초까지 보유 중인 케이스)
  const carryOverRecs = [];
  for (const dateKey in store.weeklyRecommendations) {
    if (dateKey >= weekDates[0]) continue; // 이번 주 이후는 위에서 이미 처리됨
    const arr = store.weeklyRecommendations[dateKey] || [];
    for (const r of arr) {
      if (r.type !== 'swing') continue;
      const holdDays = r.holdingDays || 3;
      const exitDate = addTradingDays(dateKey, holdDays);
      if (exitDate >= weekDates[0]) carryOverRecs.push({ ...r, date: dateKey, carryOver: true });
    }
  }

  if (recs.length === 0 && carryOverRecs.length === 0) {
    const msg = '[주간 스윙 리포트]' + NL +
      '📅 ' + weekDates[0] + ' ~ ' + weekDates[weekDates.length - 1] + NL + NL +
      '이번 주 스윙 추천 없음';
    try { await telegram.send(msg); } catch (e) {}
    return [{ json: { sent: true, count: 0 } }];
  }

  const allRecs = recs.concat(carryOverRecs);

  // [BUGFIX-2026-07-19] 거래 자체가 없던 날(상한가 잠김 등) 판별 — Naver 일봉 API는
  // 이런 날 open/high/low/volume을 전부 0으로 반환하는데, 이를 그대로 두면
  // "저가 0 <= 진입가/손절가"가 항상 참이 되어 실제로 닿지 않은 가격을 도달했다고
  // 오판정하는 버그가 생긴다 (2026-07-13~18 주간 리포트 QA에서 한성기업/003680 확인).
  const isTradedDay = (day) => Number(day.accumulatedTradingVolume) > 0;

  // [BUGFIX-2026-07-19] 목표가/손절가가 같은 날짜에 함께 도달하면 일봉만으로는 선후관계를
  // 알 수 없어 "목표가 먼저"로 낙관 판정하던 버그(동화약품/000020 2026-07-16 케이스로 확인:
  // 실제로는 09:01에 이미 목표가 초과 후 급락, 15:13에 진입가·손절가가 동시에 찍힘).
  // 분봉으로 실제 진입 체결 시각 이후 목표가/손절가 중 무엇이 먼저 찍혔는지 재확인한다.
  // 분봉 조회 실패 시(오래된 날짜 등) 기존 일봉 기준 로직으로 안전하게 폴백한다.
  const resolveSameDayOrder = async (code, dateStr, entry, target, stop) => {
    const minuteData = await naver.fetchMinute(code, dateStr);
    if (!minuteData) return null;
    let entryTime = null;
    for (const bar of minuteData) {
      if (Number(bar.lowPrice) <= entry) { entryTime = bar.localDateTime; break; }
    }
    if (!entryTime) return null; // 분봉상 진입 체결 확인 불가 → 폴백
    let targetTime = null;
    let stopTime = null;
    for (const bar of minuteData) {
      if (bar.localDateTime < entryTime) continue;
      if (!targetTime && target && Number(bar.highPrice) >= target) targetTime = bar.localDateTime;
      if (!stopTime && stop && Number(bar.lowPrice) <= stop) stopTime = bar.localDateTime;
    }
    if (targetTime && stopTime) return targetTime <= stopTime ? 'target' : 'stop';
    if (targetTime) return 'target';
    if (stopTime) return 'stop';
    return 'neither';
  };

  // ===== 성과 평가: 매수가 진입 여부 + 목표가/손절가 도달 여부 =====
  const details = [];
  let wins = 0;
  let partialWins = 0;
  let losses = 0;
  let notEntered = 0;

  for (const r of allRecs) {
    try {
      const holdDays = r.holdingDays || 3;
      const exitDate = addTradingDays(r.date, holdDays);
      // exitDate가 미래인 경우 prevTradingDay 사용 (비거래일 endDate → Naver API 빈배열 방지)
      const endCheck = exitDate <= today ? exitDate : prevTradingDay;

      const startStr = r.date.replace(/-/g, '');
      const endStr = endCheck.replace(/-/g, '');

      const data = await naver.fetchDaily(r.code, startStr, endStr);

      if (!data) {
        // [2026-07-25] no_data는 종목별 데이터 부재뿐 아니라 Naver 응답 파싱 실패(BOM/Buffer 등)로도
        // 발생할 수 있다 — 원인 추적을 위해 반드시 로그를 남긴다(과거엔 조용히 리포트에서만 빠졌음).
        logger.warning('naver fetchDaily returned no data', { code: r.code, date: r.date, startStr, endStr }, requestId);
        details.push({ ...r, result: 'no_data', maxReturn: 0, finalReturn: 0, exitDate });
        await sleep(400);
        continue;
      }

      // 추천일 ~ exitDate 범위 필터
      const recDateStr = r.date.replace(/-/g, '');
      const exitDateStr = exitDate.replace(/-/g, '');
      const relevant = data.filter((d) => d.localDate >= recDateStr && d.localDate <= exitDateStr);

      // W-002 수정: relevant 비어있으면 데이터 없음으로 처리 (not_entered 오판정 방지)
      if (relevant.length === 0) {
        details.push({ ...r, result: 'no_data', maxReturn: 0, finalReturn: 0, exitDate });
        await sleep(400);
        continue;
      }

      // ===== 매수가 진입 여부 확인 =====
      // 추천 매수가(r.entry)에 저가(low)가 도달했을 때 진입으로 판정
      // [BUGFIX-2026-07-19] 거래 없던 날(0값)은 평가에서 제외 — 위 isTradedDay 설명 참고
      let entryHit = !r.entry || r.entry <= 0; // 매수가 미설정 시 진입 간주
      for (const day of relevant) {
        if (!isTradedDay(day)) continue;
        if (Number(day.lowPrice) <= r.entry) {
          entryHit = true;
          break;
        }
      }

      // 매수가 미진입 → 리포트 제외
      if (!entryHit) {
        notEntered++;
        details.push({ ...r, result: 'not_entered', maxReturn: 0, finalReturn: 0, exitDate });
        await sleep(400);
        continue;
      }

      let result = exitDate > today ? 'holding' : 'expired';
      let maxHigh = r.entry || 0;
      let finalClose = r.entry || 0;
      let hitTargetDay = null;
      let hitTarget1Day = null;
      let hitStopDay = null;
      let stopAtHitDay = null; // hitStopDay 당일 장 시작 시점에 실제로 걸려 있던 stop (분봉 재확인용)

      // [FIX-2026-08-22] 손절일은 "지금 시점의(이미 트레일링으로 올라간) stop"을 과거 저가에
      // 소급 적용하지 않고, entry일부터 day-by-day로 Daily_Position_Monitor와 동일한 트레일링을
      // 재현하며 그날그날의 stop과 비교한다 — 그래야 급등 후 반납한 종목이 "랠리 시작 전에 이미
      // 손절됐다"는 식으로 잘못 앞당겨 판정되지 않는다(target 도달일보다 먼저 찍혀 win이 loss로
      // 뒤집히는 오분류의 원인이었음). initialStop이 없는 과거 레코드는 현재 stop으로 폴백한다.
      // 실제 운영에서 트레일링은 "그날 장이 끝난 뒤" 갱신되므로, 그날 저가는 "전날까지 갱신된
      // stop"과 비교한 다음에(순서 중요) 그날 고가/이득으로 다음날 stop을 갱신해야 한다.
      let runningStop = (r.initialStop != null ? r.initialStop : r.stop) || 0;

      for (const day of relevant) {
        const high = Number(day.highPrice);
        const low = Number(day.lowPrice);
        finalClose = Number(day.closePrice);
        // [BUGFIX-2026-07-19] 거래 없던 날(0값)은 고가/저가 도달판정에서 제외.
        // finalClose는 halt 당일에도 유효한(직전가 고정) 값이라 continue 이전에 갱신한다.
        if (!isTradedDay(day)) continue;
        if (high > maxHigh) maxHigh = high;
        if (!hitTargetDay && r.target && high >= r.target) {
          hitTargetDay = day.localDate.slice(0, 4) + '-' + day.localDate.slice(4, 6) + '-' + day.localDate.slice(6, 8);
        }
        if (!hitTarget1Day && r.target1 && high >= r.target1) {
          hitTarget1Day = day.localDate.slice(0, 4) + '-' + day.localDate.slice(4, 6) + '-' + day.localDate.slice(6, 8);
        }
        if (!hitStopDay && runningStop > 0 && low <= runningStop) {
          hitStopDay = day.localDate.slice(0, 4) + '-' + day.localDate.slice(4, 6) + '-' + day.localDate.slice(6, 8);
          stopAtHitDay = runningStop;
        }
        if (r.entry > 0 && runningStop > 0) {
          const tierGain = (high - r.entry) / r.entry;
          const atr = getAtr(r.atrAbs, high, low, finalClose);
          runningStop = calcTrailingStop(r.entry, high, atr, tierGain, runningStop);
        }
      }

      // 목표/손절 중 먼저 도달한 것 기준 판정
      // partial_win: 1차 목표 달성 후 손절 (이익 실현 일부)
      if (hitTargetDay && hitStopDay && hitTargetDay === hitStopDay) {
        // [BUGFIX-2026-07-19] 같은 날 동시 도달 — 일봉만으로는 선후관계 불명, 분봉으로 재확인
        const order = await resolveSameDayOrder(r.code, hitTargetDay, r.entry, r.target, stopAtHitDay);
        await sleep(300);
        if (order === 'target') result = 'win';
        else if (order === 'stop') result = 'loss';
        else if (order === 'neither') result = hitTarget1Day && hitTarget1Day <= hitStopDay ? 'partial_win' : 'loss';
        else result = 'win'; // 분봉 조회 실패(null) 시 기존 로직대로 낙관적 폴백
      } else if (hitTargetDay && hitStopDay) {
        result = hitTargetDay <= hitStopDay ? 'win' : 'loss';
      } else if (hitTargetDay) {
        result = 'win';
      } else if (hitStopDay) {
        result = hitTarget1Day && hitTarget1Day <= hitStopDay ? 'partial_win' : 'loss';
      }

      const maxReturn = r.entry > 0 ? (maxHigh - r.entry) / r.entry : 0;
      const finalReturn = r.entry > 0 ? (finalClose - r.entry) / r.entry : 0;
      const targetPct = (r.entry > 0 && r.target > 0) ? (r.target / r.entry - 1) : 0;
      // 실제로 손절이 걸렸다면 그 시점의 stop(stopAtHitDay)을, 아니면 현재 stop을 기준으로 한다.
      const stopForPct = hitStopDay && stopAtHitDay != null ? stopAtHitDay : r.stop;
      const stopPct = (r.entry > 0 && stopForPct > 0) ? (stopForPct / r.entry - 1) : 0;

      if (result === 'win') wins++;
      else if (result === 'partial_win') partialWins++;
      else if (result === 'loss') losses++;

      details.push({ ...r, result, maxReturn, finalReturn, exitDate, hitTargetDay, hitTarget1Day, hitStopDay, targetPct, stopPct });
    } catch (e) {
      logger.error('weekly reporter position evaluation failed', { code: r.code, date: r.date, error: e && e.message }, requestId);
      details.push({ ...r, result: 'error', maxReturn: 0, finalReturn: 0, exitDate: '' });
    }
    await sleep(400);
  }

  // 매수 진입 종목만 평가 대상
  const entered = details.filter((d) => d.result !== 'not_entered' && d.result !== 'no_data' && d.result !== 'error');
  // [2026-08-29] 목표달성률 = 최종 목표 100% 완주(win)만 인정. 1차달성(partial_win)은
  // "덜 번 것"이지 손실이 아니다 — 트레일링 로직상(lib/trailingStop.js TRAIL_BE_GAIN=3%)
  // target1(=target*0.6)에 닿은 시점엔 이미 손절선이 본전 이상으로 올라가 있어 실제 손절가는
  // 항상 손익분기~플러스다. 그래서 손절 리스트에 합치지 않고 별도 섹션(🎯 부분익절)으로 유지하되,
  // 헤드라인 달성률 분자에서는 제외한다(완주 못 했다는 사실은 그대로 보여줘야 함). 분모(evaluated)는
  // 기존대로 win+partial_win+loss — expired만 제외.
  const evaluated = entered.filter((d) => d.result === 'win' || d.result === 'partial_win' || d.result === 'loss');
  const winRate = evaluated.length > 0 ? wins / evaluated.length : 0;
  // 성공률(부분포함): 부분익절을 손실 아닌 성공으로 잡는 보조 지표 — 목표달성률과 나란히 표기.
  const successRate = evaluated.length > 0 ? (wins + partialWins) / evaluated.length : 0;
  const enteredCount = entered.length;

  // 섹션별 분류
  const winList = details.filter((d) => d.result === 'win');
  const partialWinList = details.filter((d) => d.result === 'partial_win');
  const lossList = details.filter((d) => d.result === 'loss');
  // [CARRYOVER] 보유 종목은 이번주 신규 추천분과 지난주 이월분을 분리해서 리포트
  const holdListAll = details.filter((d) => d.result === 'holding' || d.result === 'expired');
  const holdList = holdListAll.filter((d) => !d.carryOver);
  const holdListCarry = holdListAll.filter((d) => d.carryOver);

  // Log report statistics for QA tracing
  logger.info('Weekly report generated', {
    reportDate: today,
    totalPositions: details.length,
    wins: wins,
    partialWins: partialWins,
    losses: losses,
    holding: holdListAll.length,
    winRate: (winRate * 100).toFixed(1) + '%',
    successRate: (successRate * 100).toFixed(1) + '%',
    enteredCount: enteredCount
  }, requestId);

  // 각 섹션 내 수익률 기준 정렬
  winList.sort((a, b) => (b.maxReturn || 0) - (a.maxReturn || 0));
  holdList.sort((a, b) => (b.maxReturn || 0) - (a.maxReturn || 0));
  holdListCarry.sort((a, b) => (b.maxReturn || 0) - (a.maxReturn || 0));
  lossList.sort((a, b) => (a.maxReturn || 0) - (b.maxReturn || 0));
  partialWinList.sort((a, b) => (b.stopPct || 0) - (a.stopPct || 0));

  // ===== 깨진 종목명 보완: Naver API로 재조회 =====
  const isGarbled = (s) => !s || !/^[가-힣ᄀ-ᇿ㄰-㆏㈀-㈟！-ﾟ一-鿿 -~]+$/.test(s);
  const allCodes = [...new Set(details.map((d) => d.code))];
  for (const code of allCodes) {
    const cached = store.naverNames && store.naverNames[code];
    if (cached && cached !== code && !isGarbled(cached)) continue;
    const stored = details.find((d) => d.code === code)?.name;
    if (stored && stored !== code && !isGarbled(stored)) continue;
    try {
      const nr = await http({
        method: 'GET',
        url: 'https://m.stock.naver.com/api/stock/' + code + '/basic',
        json: true,
        headers: { 'User-Agent': 'Mozilla/5.0', 'Referer': 'https://finance.naver.com/', 'Accept-Language': 'ko-KR,ko;q=0.9' },
      });
      const nm = nr && (nr.stockName || nr.itemName || nr.name || nr.symbolName);
      if (nm && nm !== code && !isGarbled(nm)) {
        if (!store.naverNames) store.naverNames = {};
        store.naverNames[code] = nm;
      }
    } catch (e) {}
    await sleep(300);
  }

  const resolveName = (d) => {
    const cached = store.naverNames && store.naverNames[d.code];
    if (cached && cached !== d.code && !isGarbled(cached)) return cached;
    if (d.name && d.name !== d.code && !isGarbled(d.name)) return d.name;
    return d.code;
  };

  // HELPER-01: 날짜 단축 (2026-03-25 → 03-25)
  const shortDate = (ds) => (ds && ds.length >= 7) ? ds.slice(5) : (ds || '');
  // [CARRYOVER] 지난주 이월 종목 표시 태그
  const carryTag = (d) => d.carryOver ? '[이월] ' : '';

  // ===== 메시지 구성 =====
  let msg = '[주간 스윙 성과 리포트]' + NL +
    '📅 ' + weekDates[0] + ' ~ ' + weekDates[weekDates.length - 1] + NL +
    '━━━━━━━━━━━━━━━━━━━━' + NL +
    '총추천 ' + recs.length + '건' + (carryOverRecs.length > 0 ? ' (+이월 ' + carryOverRecs.length + '건)' : '') +
    ' │ 진입 ' + enteredCount + '건 │ 목표달성률 ' + (evaluated.length > 0 ? (winRate * 100).toFixed(0) + '%' : 'N/A') +
    ' (부분포함 ' + (evaluated.length > 0 ? (successRate * 100).toFixed(0) + '%' : 'N/A') + ')' + NL +
    '✅ 목표 ' + wins + '건 │ 🎯 부분익절 ' + partialWins + '건 │ ❌ 손절 ' + losses + '건 │ 🔄 보유 ' + holdList.length + '건' + NL +
    '━━━━━━━━━━━━━━━━━━━━' + NL;

  // ✅ 수익 종목
  if (winList.length > 0) {
    msg += NL + '✅ 수익 (' + winList.length + '건)' + NL;
    for (const d of winList) {
      const name = resolveName(d);
      const typeTag = d.isETF === false ? '[단일종목]' : d.isETF ? '[ETF]' : '';
      let line = carryTag(d) + typeTag + name + '(' + (d.code || '') + ') │ ' + shortDate(d.date);
      if (Number.isFinite(d.maxReturn) && d.maxReturn !== 0) line += ' │ 최고 ' + pct(d.maxReturn);
      if (d.hitTargetDay) line += ' │ ' + shortDate(d.hitTargetDay);
      if (d.grade) line += ' │ ' + d.grade;
      if (d.score) line += ' │ ' + d.score + '점';
      if (d.patternType) line += ' │ ' + d.patternType;
      if (d.signals && d.signals.length) line += ' │ ' + d.signals.join(',');
      msg += line + NL;
    }
  }

  // 🎯 1차 목표 달성 후 손절 (부분 수익 — 손실 아님, 목표달성률 분자에서만 제외)
  if (partialWinList.length > 0) {
    msg += NL + '🎯 부분익절 (' + partialWinList.length + '건, 목표 미완주)' + NL;
    for (const d of partialWinList) {
      const name = resolveName(d);
      const typeTag = d.isETF === false ? '[단일종목]' : d.isETF ? '[ETF]' : '';
      let line = carryTag(d) + typeTag + name + '(' + (d.code || '') + ') │ ' + shortDate(d.date);
      if (d.hitTarget1Day) line += ' │ 1차 ' + shortDate(d.hitTarget1Day);
      if (d.hitStopDay) line += ' │ 청산 ' + shortDate(d.hitStopDay);
      if (Number.isFinite(d.stopPct)) line += ' │ 확정 ' + pct(d.stopPct);
      if (Number.isFinite(d.maxReturn) && d.maxReturn !== 0) line += ' │ 최고 ' + pct(d.maxReturn);
      if (d.grade) line += ' │ ' + d.grade;
      if (d.score) line += ' │ ' + d.score + '점';
      if (d.patternType) line += ' │ ' + d.patternType;
      if (d.signals && d.signals.length) line += ' │ ' + d.signals.join(',');
      msg += line + NL;
    }
  }

  // 🔄 보유 종목
  if (holdList.length > 0) {
    msg += NL + '🔄 보유 (' + holdList.length + '건)' + NL;
    for (const d of holdList) {
      const name = resolveName(d);
      let line = name + '(' + (d.code || '') + ') │ ' + shortDate(d.date);
      if (Number.isFinite(d.maxReturn) && d.maxReturn !== 0) line += ' │ 최고 ' + pct(d.maxReturn);
      if (d.result === 'holding' && d.exitDate) line += ' │ 예정일 ' + shortDate(d.exitDate);
      if (d.result === 'expired') line += ' │ 보유예정일 ' + shortDate(d.exitDate || d.date);
      if (d.score) line += ' │ ' + d.score + '점';
      msg += line + NL;
    }
  }

  // 📌 이월 보유 종목 — 지난주 이전 추천, 보유기간 때문에 이번 주까지 보유 중
  if (holdListCarry.length > 0) {
    msg += NL + '📌 이월 보유 (전주 추천, ' + holdListCarry.length + '건)' + NL;
    for (const d of holdListCarry) {
      const name = resolveName(d);
      let line = name + '(' + (d.code || '') + ') │ ' + shortDate(d.date);
      if (Number.isFinite(d.maxReturn) && d.maxReturn !== 0) line += ' │ 최고 ' + pct(d.maxReturn);
      if (d.result === 'holding' && d.exitDate) line += ' │ 예정일 ' + shortDate(d.exitDate);
      if (d.result === 'expired') line += ' │ 보유예정일 ' + shortDate(d.exitDate || d.date);
      if (d.score) line += ' │ ' + d.score + '점';
      msg += line + NL;
    }
  }

  // ❌ 손절 종목 (진짜 손실 — 1차 목표조차 못 찍고 손절가 도달)
  if (lossList.length > 0) {
    msg += NL + '❌ 손절 (' + lossList.length + '건)' + NL;
    for (const d of lossList) {
      const name = resolveName(d);
      const typeTag = d.isETF === false ? '[단일종목]' : d.isETF ? '[ETF]' : '';
      let line = carryTag(d) + typeTag + name + '(' + (d.code || '') + ') │ ' + shortDate(d.date);
      if (Number.isFinite(d.maxReturn) && d.maxReturn !== 0) line += ' │ 최고 ' + pct(d.maxReturn);
      if (Number.isFinite(d.stopPct)) line += ' │ 확정 ' + pct(d.stopPct);
      if (d.hitStopDay) line += ' │ 손절 ' + shortDate(d.hitStopDay);
      if (d.grade) line += ' │ ' + d.grade;
      if (d.score) line += ' │ ' + d.score + '점';
      if (d.patternType) line += ' │ ' + d.patternType;
      if (d.signals && d.signals.length) line += ' │ ' + d.signals.join(',');
      msg += line + NL;
    }
    // [QI-5] 손절 카운터 갱신 — 당일 손절 카운트를 store에 기록
    // (스캐너가 다음 실행 시 이 값을 읽어 당일 발송 억제 여부 결정)
    try {
      if (!store.intradayStopCount) store.intradayStopCount = {};
      for (const d of lossList) {
        const stopDay = d.hitStopDay || d.date;
        if (!store.intradayStopCount[stopDay]) store.intradayStopCount[stopDay] = 0;
        store.intradayStopCount[stopDay]++;
      }
    } catch(e) {}
  }

  // 매수 미진입 종목 + [QI-4] 미도달 이후 추적 (2026-05-09)
  const notEnteredList = details.filter((d) => d.result === 'not_entered');
  const missedOpportunities = []; // 미도달 후 상승 종목
  if (notEnteredList.length > 0) {
    // 미도달 종목의 이후 3거래일 가격 추적
    for (const d of notEnteredList) {
      try {
        const trackEnd = addTradingDays(d.date, 3);
        const trackEndCheck = trackEnd <= today ? trackEnd : prevTradingDay;
        const startStr = addTradingDays(d.date, 1).replace(/-/g, '');
        const endStr = trackEndCheck.replace(/-/g, '');
        if (startStr > endStr) continue;
        const trackData = await naver.fetchDaily(d.code, startStr, endStr);
        await sleep(300);
        if (!trackData || trackData.length === 0) continue;
        const postHigh = Math.max(...trackData.map(r => Number(r.highPrice) || 0));
        const postLow  = Math.min(...trackData.map(r => Number(r.lowPrice) || Infinity));
        const postReturn = d.entry > 0 ? (postHigh - d.entry) / d.entry : 0;
        // 미도달 후 3일 이내 +3% 이상 상승 → 기회 손실로 분류
        if (postReturn >= 0.03) {
          missedOpportunities.push({ ...d, postReturn, postHigh });
        }
      } catch(e) { /* 추적 실패 무시 */ }
    }

    msg += NL + '⚪ 매수 미도달 (' + notEnteredList.length + '건)' + NL;
    for (const d of notEnteredList) {
      const name = resolveName(d);
      msg += carryTag(d) + name + '(' + (d.code || '') + ') │ ' + shortDate(d.date) + NL;
    }
  }

  // [QI-4] 미도달 후 상승 섹션 — 진입가 재검토 시그널
  if (missedOpportunities.length > 0) {
    msg += NL + '⚡ 미도달 후 상승 (진입가 재검토 권장)' + NL;
    for (const d of missedOpportunities) {
      const name = resolveName(d);
      msg += name + '(' + (d.code || '') + ') │ ' + shortDate(d.date) + ' │ 이후최고 +' + (d.postReturn * 100).toFixed(1) + '%' + NL;
    }
    // 미도달+이후상승 건수를 store에 누적 (3주 연속 발생 시 경고)
    try {
      if (!store.missedEntryHistory) store.missedEntryHistory = [];
      store.missedEntryHistory.push({ week: weekDates[0], count: missedOpportunities.length });
      store.missedEntryHistory = store.missedEntryHistory.slice(-6); // 최근 6주만 보관
      const recentHighMiss = store.missedEntryHistory.slice(-3).filter(h => h.count >= 2).length;
      if (recentHighMiss >= 3) {
        msg += '⚠️ 3주 연속 미도달+상승 다수 — 진입가를 시가(오픈가) 기준으로 전환 검토 필요' + NL;
      }
    } catch(e) {}
  }

  msg += NL + '⚠️ 본 리포트는 참고용이며 투자 결과에 책임지지 않습니다.';

  // Telegram 4096자 초과 시 분리 전송
  const TELE_LIMIT = 4000;
  const chunks = [];
  if (msg.length <= TELE_LIMIT) {
    chunks.push(msg);
  } else {
    let remaining = msg;
    while (remaining.length > 0) {
      if (remaining.length <= TELE_LIMIT) { chunks.push(remaining); break; }
      let cut = remaining.lastIndexOf(NL, TELE_LIMIT);
      if (cut <= 0) cut = TELE_LIMIT;
      chunks.push(remaining.slice(0, cut));
      remaining = remaining.slice(cut).replace(/^\n/, '');
    }
  }

  for (let ci = 0; ci < chunks.length; ci++) {
    try {
      await telegram.send(chunks[ci]);
    } catch (e) {}
    if (ci < chunks.length - 1) await sleep(500);
  }

  // Log report completion
  logger.info('Weekly report sent', {
    reportDate: today,
    messageChunks: chunks.length,
    totalChars: msg.length,
    positions: recs.length,
    enteredCount: enteredCount
  }, requestId);

  return [{ json: { sent: true, count: recs.length, enteredCount, wins, losses, winRate } }];
};
return run();
